export {
  colorIndigo,
  colorCrimson,
  colorCoral,
  colorOrcher,
  colorYellow,
  colorCobalt,
  colorFucshia,
  colorGray,
  colorPrimary,
  colorSecondary,
  colorTertiary,
  colorText,
  fontFamily,
  fontFamilyTitle,
  fontSizeMobile,
  fontSizeDesktop,
  fontWeight,
  fontSpacing,
  fontLineheight,
  gridBreackpoints,
  gridContainerWidth,
  gridColumns,
  gridGutter,
  gridSpacer,
  colorMarsBase,
  colorPrimaries,
  colorFundations,
  fontFundations,
} from './src/fundations.js';
export { tagsFont } from './src/tags.js';
